// -*- Mode: c++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
//
// Copyright (C) 2013 Opera Software ASA.  All rights reserved.
//
// This file is an original work developed by Opera Software ASA

/** User authentication failure. */
SYNC_SERVER_ERROR(AUTH_TOKEN_INVALID, 101)
/** The authorization token has expired and a new one must be obtained. */
SYNC_SERVER_ERROR(AUTH_TOKEN_EXPIRED, 103)
