/* -*- Mode: c; indent-tabs-mode: nil; c-basic-offset: 4; -*-
 *
 * Copyright (C) 2012 Software ASA.  All rights reserved.
 *
 * This file is part of the Opera web browser.  It may not be distributed
 * under any circumstances.
 */

#ifndef _REKSIO_ANDROID_FEATURES_COMMON_H_
#define _REKSIO_ANDROID_FEATURES_COMMON_H_

/* Mini5+ must define MOP_BREAM */
#define MOP_BREAM

/* Bream Graphics */

#define BREAM_GRAPHICS_THREAD_USE_PTHREAD
#define BREAM_GRAPHICS_IMAGE_ATOMIC_REFCOUNT
#define BREAM_GRAPHICS_OBML_MIXEDBLOCKS
#define BREAM_GRAPHICS_ENABLE_FLOAT
#define BREAM_GRAPHICS_OBML_CHARPOS_BYTE
#define BREAM_GRAPHICS_GLES1
#define BREAM_GRAPHICS_OBML_LOCKDOCUMENT
#define BREAM_GRAPHICS_GL_HEADER "GLES/gl.h"
#define BREAM_GRAPHICS_GLES1_THREADCOMPATIBLE
#define BREAM_GRAPHICS_TILESCONTAINER_NUM_VIEWPORTS 3
#define DEBUG_DEADLOCK_THRESHOLD 2

#define MOP_TWEAK_PLATFORM_GETBGFONT

/* core/features.txt */

#define MOP_USE_FEATURE_ALPHA YES
#define MOP_USE_FEATURE_APPEND_ORIGINAL_REQUEST_URL NO
#define MOP_USE_FEATURE_AUTOCOMPLETE YES
#define MOP_USE_FEATURE_AUTOPROBE NO
#define MOP_USE_FEATURE_AUTO_UPDATE NO
#define MOP_USE_FEATURE_BACKBUFFER NO
#define MOP_USE_FEATURE_BANURLS NO
#define MOP_USE_FEATURE_BDFENGINE_IMPLEMENTATION NO
#define MOP_USE_FEATURE_BDFSUPPORT NO
#define MOP_USE_FEATURE_BDF_FONTSCOLLECTION NO
#define MOP_USE_FEATURE_BREAM_GRAPHICS YES
#define MOP_USE_FEATURE_BREAM_THREADSAFE_OBMLPAINTER YES
#define MOP_USE_FEATURE_BREAM_TILING YES
#define MOP_USE_FEATURE_CLIENTSIDE_DOWNLOAD YES
#define MOP_USE_FEATURE_CLIENT_SIDE_HTTP_AUTH YES
#define MOP_USE_FEATURE_CLIENT_SIDE_JS_ALERT NO
#define MOP_USE_FEATURE_CLIENT_SIDE_JS_DIALOGS YES
#define MOP_USE_FEATURE_CRYPTOSTREAM YES
#define MOP_USE_FEATURE_DATASTORE YES
#define MOP_USE_FEATURE_DELAYED_DECODING NO
#define MOP_USE_FEATURE_DELAY_PAINT YES
#define MOP_USE_FEATURE_DLITE_NATIVEOPEN NO
#define MOP_USE_FEATURE_DOCUMENT_FILE_SUPPORT NO
#define MOP_USE_FEATURE_DOWNLOAD_STATS NO
#define MOP_USE_FEATURE_DUMMYFONTINFO NO
#define MOP_USE_FEATURE_DUMP_OBSP NO
#define MOP_USE_FEATURE_EXTENDED_FONTINFO YES
#define MOP_USE_FEATURE_EXTENDED_FONTINFO_MANY_FACES NO
#define MOP_USE_FEATURE_EXTENDED_FONTINFO_MANY_SIZES NO
#define MOP_USE_FEATURE_FILEOBSPSTREAM NO
#define MOP_USE_FEATURE_FILESYSTEM NO
#define MOP_USE_FEATURE_FILE_DOWNLOAD YES
#define MOP_USE_FEATURE_FILE_UPLOAD YES
#define MOP_USE_FEATURE_FIND_IN_PAGE YES
#define MOP_USE_FEATURE_FONTINFO_DUMP NO
#define MOP_USE_FEATURE_FONTINFO_READ NO
#define MOP_USE_FEATURE_FONTMANAGER_ADD_FAKE_FONT YES
#define MOP_USE_FEATURE_FONTZOOMSETTING NO
#define MOP_USE_FEATURE_FONT_INSPECTOR NO
#define MOP_USE_FEATURE_FONT_SCALE YES
#define MOP_USE_FEATURE_FONT_TOOL NO
#define MOP_USE_FEATURE_GENERIC_KEYCHAIN YES
#define MOP_USE_FEATURE_GENERIC_LANDSCAPE NO
#define MOP_USE_FEATURE_GLOBAL_HISTORY NO
#define MOP_USE_FEATURE_GLOBAL_IMAGES_CACHE YES
#define MOP_USE_FEATURE_HTTPSTREAM YES
#define MOP_USE_FEATURE_HTTP_ADDITIONAL_HEADERS NO
#define MOP_USE_FEATURE_HTTP_CHUNKED_DECODER NO
#define MOP_USE_FEATURE_HTTP_PLATFORM_PROXY YES
#define MOP_USE_FEATURE_ICONSTORAGE NO
#define MOP_USE_FEATURE_INTERNAL_PAGES_SUPPORT NO
#define MOP_USE_FEATURE_KEYCHAIN YES
#define MOP_USE_FEATURE_LEA_MALLOC NO
#define MOP_USE_FEATURE_LH_STOREVIEWPORT NO
#define MOP_USE_FEATURE_LIGHTWEIGHT_DOCUMENT_SUPPORT YES
#define MOP_USE_FEATURE_LOCK_VM NO
#define MOP_USE_FEATURE_LOG_SLICES NO
#define MOP_USE_FEATURE_MEMORY_TEST NO
#define MOP_USE_FEATURE_MSGLOOP_DISABLE_CACHE NO
#define MOP_USE_FEATURE_NETWORK_TESTS YES
#define MOP_USE_FEATURE_OBML_CACHE NO
#define MOP_USE_FEATURE_OBSP_SEND_FILE_REQUEST NO
#define MOP_USE_FEATURE_ODP NO
#define MOP_USE_FEATURE_OLD_PAINTER NO
#define MOP_USE_FEATURE_PAINTERPI_EXTENDED YES
#define MOP_USE_FEATURE_PLATFORMFONT NO
#define MOP_USE_FEATURE_PLATFORM_FONTS_COLLECTION NO
#define MOP_USE_FEATURE_PLATFORM_LANDSCAPE NO
#define MOP_USE_FEATURE_PLATFORM_REQUEST YES
#define MOP_USE_FEATURE_PLATFORM_RES_STREAM YES
#define MOP_USE_FEATURE_PRESTORAGE_ROM NO
#define MOP_USE_FEATURE_PRIVATE_MODE YES
#define MOP_USE_FEATURE_PROBE NO
#define MOP_USE_FEATURE_PROBE_OBML_IMAGE NO
#define MOP_USE_FEATURE_PROBE_RENDERER NO
#define MOP_USE_FEATURE_PROGRESSIVE_OBML_LOADING YES
#define MOP_USE_FEATURE_PUTTY_ZLIB NO
#define MOP_USE_FEATURE_RENDERERGROUPS MOP_USE_FEATURE_ODP
#define MOP_USE_FEATURE_RICH_DOCUMENT_SUPPORT NO
#define MOP_USE_FEATURE_RICH_FONTS NO
#define MOP_USE_FEATURE_SEARCHES NO
#define MOP_USE_FEATURE_SH_IMAGE_INDEXER NO
#define MOP_USE_FEATURE_SOCKETSTREAM YES
#define MOP_USE_FEATURE_SOFTKEYS_COMMANDS NO
#define MOP_USE_FEATURE_SPECIALLINK YES
#define MOP_USE_FEATURE_SPEEDDIAL NO
#define MOP_USE_FEATURE_STATISTICS NO
#define MOP_USE_FEATURE_SUPPORTS_BIDI YES
#define MOP_USE_FEATURE_SWITCHABLE_COMPRESSION NO
#define MOP_USE_FEATURE_TEXT_SELECTION YES
#define MOP_USE_FEATURE_THUMBNAIL NO
#define MOP_USE_FEATURE_TRACK_INSTALLS YES
#define MOP_USE_FEATURE_TRACK_CLIENTS NO
#define MOP_USE_FEATURE_TRAFFIC_ROUTING YES
#define MOP_USE_FEATURE_USER_STATS YES
#define MOP_USE_FEATURE_VEGA NO
#define MOP_USE_FEATURE_VFILE NO
#define MOP_USE_FEATURE_ZLIB YES
#define MOP_USE_PLATFORM_ZLIB YES /* Use NDK zlib. */

/* core/have.txt */

#define MOP_HAVE_GET_SCREEN_DIMENSIONS
#define MOP_HAVE_NOT_TWEAKED_CLIENT_VERSION
#define MOP_HAVE_TWEAKED_FORM_FACTOR
#define MOP_HAVE_TWEAKED_IS_TOUCH
#define MOP_HAVE_FONT_SCALE_RUNTIME_DETECT
#define MOP_HAVE_GETINSTALLREFERRER
#define MOP_HAVE_GETMCC
#define MOP_HAVE_GETMNC
#define MOP_HAVE_GETSCREENDPI
#define MOP_HAVE_SM_MODIFY_DEFAULTS

/* core/tweak.txt */

#define MOP_TWEAK_BASE_CLASS_HAS_ATOMIC_REFCOUNT
#define MOP_TWEAK_BRANDING MOP_TWEAK_DEFAULT_BRANDING
#define MOP_TWEAK_DEFAULT_BRANDING T(DEFAULT_BRANDING)
#define MOP_TWEAK_PRODUCT_NAME T(MOP_PRODUCT_NAME)
#define MOP_CLIENT_CPU CLIENT_CPU
#ifdef BETA
# define MOP_RELEASE_CHANNEL OBSP_REQUEST_RELEASE_BETA
#else
# define MOP_RELEASE_CHANNEL OBSP_REQUEST_RELEASE_STANDARD
#endif
#define MOP_HAVE_AU_GETCLIENTDISTRIBUTIONSOURCE
#define MOP_TWEAK_DEFAULT_SETTINGS_FILE_SECURE
#define MOP_TWEAK_DOWNLOAD_WITH_OBSP
/* If you tweak this size also consider tweaking the preallocated
   arrays in Font.java */
#define MOP_TWEAK_FONTINFO_GENERATION_BATCH_SIZE 0x60
#define MOP_TWEAK_FONTINFO_GENERATION_SLICE_SIZE 0x60
#define MOP_TWEAK_HICOLOR_THUMBNAILS
#define MOP_TWEAK_GET_BRANDING
#define MOP_TWEAK_IMAGES_CACHE_COUNT -1
#define MOP_TWEAK_IMAGES_CACHE_MAXSIZE (16 * 1024 * 1024)
#define MOP_TWEAK_MAX_AVAIL_MEMORY (32 * 1024 * 1024)
#define MOP_TWEAK_PLATFORM_FONT_SALT 1
#define MOP_TWEAK_REMOVE_UNSUPPORTED_CODE
#define MOP_TWEAK_PLATFORM_DATASTORE
#define MOP_TWEAK_ENABLE_CONNECTION_RETRY
#define MOP_TWEAK_DEFAULT_MINI_SERVER MOP_GLOBAL_MINI_SERVER
#define MOP_TWEAK_OBML_RELATIVE_COORDINATES

/* Our data store implementation does not use a METAFILE. */
#define MOP_BREAM_DATASTORE_METAFILE NULL

/* core misc */

#define OBSP_PLATFORM_NAME OBSP_REQUEST_PLATFORM_ANDROID
// Only have a single logical OBSP connection per socket. Fixes problems with
// having more than a single download active at the same time. When pausing a
// download, the socket is closed to prevent any more data from being sent. If
// another download shares the same socket, it will be stopped (which will be
// shown as "failed" in the UI).
#define OBSPCONNECTION_MAX_CONNECTIONS 1

/* generic/features.txt */

#define MOP_USE_FEATURE_APP_STATS NO
#define MOP_USE_FEATURE_BREAM_DATASTORE YES
#define MOP_USE_FEATURE_DICTIONARY NO
#define MOP_USE_FEATURE_DYNHOMEPAGE NO
#define MOP_USE_FEATURE_EXTENDED_DEBUG NO
#define MOP_USE_FEATURE_KEYBOARD_ROTATE_ARROW_KEYS NO
#define MOP_USE_FEATURE_METAVIEWPORT YES
#define MOP_USE_FEATURE_MULTITOUCH NO
#define MOP_USE_FEATURE_NATIVE_NETWORK YES
#define MOP_USE_FEATURE_PAINT_THREAD NO
#define MOP_USE_FEATURE_PINCHZOOM NO
#define MOP_USE_FEATURE_PROBE_NODE_PAINTER NO
#define MOP_USE_FEATURE_REACHABILITY YES
#define MOP_USE_FEATURE_RESOURCE_DOWNLOAD NO
#define MOP_USE_FEATURE_REVALIDATE_IMAGES NO
#define MOP_USE_FEATURE_SAVEDPAGES YES
#define MOP_USE_FEATURE_SCROLLVIEW NO
#define MOP_USE_FEATURE_SHORTCUTMANAGER NO
#define MOP_USE_FEATURE_SHORTCUTMANAGER_IDENTS NO
#define MOP_USE_FEATURE_SHORTCUTMANAGER_KEYSTRING NO
#define MOP_USE_FEATURE_STREAMING_DOWNLOAD YES
#define MOP_USE_FEATURE_TOUCHSCREEN YES
#define MOP_USE_FEATURE_VM_SPLIT_RESOURCES NO
#define MOP_USE_FEATURE_VM_STRINGS NO
#define MOP_USE_FEATURE_VOICESEARCH NO
#define MOP_USE_FEATURE_WEBP_DECODER YES

/* generic/have.txt */

#define MOP_HAVE_IS_TABLET
// TODO We should just remove the stuff in Obml.inl that depends on clipboard
// support (ContextMenuInfo.performAction) - e.g. expose functions to get the
// text and let the Bream UI move it to the clipboard.
//#define MOP_HAVE_PLATFORM_CLIPBOARD

/* generic/tweak.txt */

#define MOP_TWEAK_DISABLE_SPLASH
#define MOP_TWEAK_EXTERNAL_VM_INSTANCE
#define MOP_TWEAK_DRM_DOWNLOAD

#define MOP_GENERIC_VERSION VERSION_NUMBER
#define MOP_BUILD_NUMBER BUILDNUMBER

#define DEVELOPER_CLUSTER_KEY \
    T("qdr/oXTGO3K2n9rot6cRiblhLsF6oEip0asmVQ7E1IpkWOHlcVpXSuSG5Wa26") \
    T("VncwKeYuIocAc3/51YGgfYS02bYAfbhNh5dxF1vJdRiqpUm3EAUkHft8+A7XZ") \
    T("2Q1cqoaehGlPohDJUdQPgBRyvUxSGPCF/pvrbJ7GeTp4xbB33RvRPPzVp1bUR") \
    T("00Ih3IBypbsQXq7z061wjurE4RXrFmQ==")
#define PRESS_DEMO_KEY \
    T("XYf32CJd0j/eSHCSYcbM6gZnhy5/hXjnAN8OYxWrEn8DTjTiYJAlkbJiEE1Vc2thI5Txur4VWAGQqHDnTE83ZBvm8+rRPwVArFTzpoy4cN0Cd1fdRZINbgQiElGICYZy7qBDoUwUElfnMS0S/V2G60P/PRSZiVfeaRaUyB0JSAc8oMPtNoieDKM+lc8jCoP3K9RkDmBVeaD5KyC4vEiFlw==")
#define CUST_DEMO_CLUSTER_KEY \
    T("gH4nf4ncABe904wpZZeaJhfXneL7bE+oipuArn4scMdSmB8Dbv8cAt6ld9ObA") \
    T("nFkP6pV5tPncIZwOvx5EXD45K2NKuY8s1VL6hOD+MHNb/Zutvoac+RjY15Why") \
    T("DxBtHe4jPEhmTcyGt3VTV2MpJe7CQVs8AHzD+WWCfcxoSbNdbI3P9McaGn9yQ") \
    T("y5pCMS/pqMttr6Vttb2jvMC5xzOOCXQ==")

#ifdef DEVELOPER_CLUSTER
# define MOP_TWEAK_CRYPTOSTREAM_MASTER_KEY DEVELOPER_CLUSTER_KEY
# define MOP_TWEAK_MINISERVER_SOCKET T("socket://developer-test.opera-mini.net:1080")
# define MOP_TWEAK_MINISERVER_HTTP T("http://developer-test.opera-mini.net:80")
#elif defined(PRESS_DEMO_CLUSTER)
# define MOP_TWEAK_CRYPTOSTREAM_MASTER_KEY PRESS_DEMO_KEY
# define MOP_TWEAK_MINISERVER_SOCKET T("socket://press-demo-test.opera-mini.net:1080")
# define MOP_TWEAK_MINISERVER_HTTP T("http://press-demo-test.opera-mini.net:80")
#elif defined(TEST_MINI_4_CLUSTER)
# define MOP_TWEAK_CRYPTOSTREAM_MASTER_KEY DEVELOPER_CLUSTER_KEY
# define MOP_TWEAK_MINISERVER_SOCKET T("socket://test-mini4-test.opera-mini.net:1080")
# define MOP_TWEAK_MINISERVER_HTTP T("http://test-mini4-test.opera-mini.net:80")
#elif defined(QA_TEST_CLUSTER)
# define MOP_TWEAK_CRYPTOSTREAM_MASTER_KEY DEVELOPER_CLUSTER_KEY
# define MOP_TWEAK_MINISERVER_SOCKET T("socket://test-qa-test.opera-mini.net:1080")
# define MOP_TWEAK_MINISERVER_HTTP T("http://test-qa-test.opera-mini.net:80")
#elif defined(TEST_GLOBAL_CLUSTER)
# define MOP_TWEAK_CRYPTOSTREAM_MASTER_KEY DEVELOPER_CLUSTER_KEY
# define MOP_TWEAK_MINISERVER_SOCKET T("socket://test-global-test.opera-mini.net:1080")
# define MOP_TWEAK_MINISERVER_HTTP T("http://test-global-test.opera-mini.net:80")
#elif defined(CUST_DEMO_CLUSTER)
# define MOP_TWEAK_CRYPTOSTREAM_MASTER_KEY CUST_DEMO_CLUSTER_KEY
# define MOP_TWEAK_MINISERVER_SOCKET T("socket://cust-demo-test.opera-mini.net:1080")
# define MOP_TWEAK_MINISERVER_HTTP T("http://cust-demo-test.opera-mini.net:80")
#elif defined(TEST_GLB_CLUSTER)
# define MOP_TWEAK_CRYPTOSTREAM_MASTER_KEY DEVELOPER_CLUSTER_KEY
# define MOP_TWEAK_MINISERVER_SOCKET T("socket://test-glb-test.opera-mini.net:1080")
# define MOP_TWEAK_MINISERVER_HTTP T("http://test-glb-test.opera-mini.net:80")
#elif defined(CUSTOM_CLUSTER)
# ifndef CUSTOM_CLUSTER_MASTER_KEY
#  define MOP_TWEAK_CRYPTOSTREAM_MASTER_KEY MOP_GLOBAL_CLUSTER_MASTER_KEY
# else
#  define MOP_TWEAK_CRYPTOSTREAM_MASTER_KEY T(CUSTOM_CLUSTER_MASTER_KEY)
# endif /* !CUSTOM_CLUSTER_MASTER_KEY */
# define MOP_TWEAK_MINISERVER_SOCKET T("socket://" CUSTOM_CLUSTER_HOST ":1080")
# define MOP_TWEAK_MINISERVER_HTTP T("http://" CUSTOM_CLUSTER_HOST ":80")
#elif !defined(GLOBAL_CLUSTER)
# error "Unknown mini cluster"
#endif

#if !defined(CUSTOM_CLUSTER) && !defined(GLOBAL_CLUSTER)
// Prevent loading resources from global instead of test/demo clusters
# ifndef MOP_TWEAK_NO_THUMBNAIL_TRAFFIC_ROUTING_RULE
#  define MOP_TWEAK_NO_THUMBNAIL_TRAFFIC_ROUTING_RULE
# endif /* MOP_TWEAK_NO_THUMBNAIL_TRAFFIC_ROUTING_RULE */
#endif /* !defined(CUSTOM_CLUSTER) && !defined(GLOBAL_CLUSTER) */

#ifndef GLOBAL_CLUSTER
# undef MOP_TWEAK_DEFAULT_MINI_SERVER
# define MOP_TWEAK_DEFAULT_MINI_SERVER MOP_CUSTOM_MINI_SERVER
#endif

/* Debug flags */

#ifndef NDEBUG
#define BREAM_DEBUG
#define BREAM_DEBUGGER_SUPPORT 0
#define MOP_HAVE_DEBUG
#define MOP_HAVE_DEBUG_EX
#define MOP_USE_FEATURE_BOOTLOGGING YES
#else
#define MOP_USE_FEATURE_BOOTLOGGING NO
#endif

#ifdef MOP_HAVE_DEBUG
# define MOP_DEBUG_PRINT(format, args...) MOpDebug_print((format), ##args)
# ifdef MOP_HAVE_DEBUG_EX
#  define MOP_DEBUG_PRINTEX(scope, severity, format, args...)           \
    MOpDebugEx_print(__FILE__, __LINE__, (scope), (severity), (format), ##args)
# else /* MOP_HAVE_DEBUG_EX */
#  define MOP_DEBUG_PRINTEX(scope, severity, format, args...)   \
    MOpDebug_print((format), ##args)
# endif /* MOP_HAVE_DEBUG_EX */
#else /* MOP_HAVE_DEBUG */
# define MOP_DEBUG_PRINT(format, args...)
# define MOP_DEBUG_PRINTEX(scope, severity, format, args...)
#endif /* MOP_HAVE_DEBUG */

#define MOP_FEATURE_TRAFFIC_ROUTING
#define MOP_TWEAK_THREADSAFE_TRAFFIC_ROUTING

// Keep include last since it may check and define values
// we want to override if not defined already
#include "mini/c/shared/generic/config/features-mini5_default.h"

#endif /* _REKSIO_ANDROID_FEATURES_COMMON_H_ */
