// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     com/opera/android/utilities/DisplayUtil

#ifndef com_opera_android_utilities_DisplayUtil_JNI
#define com_opera_android_utilities_DisplayUtil_JNI

#include <jni.h>

#include "../../../../../../../../../../../../../../../base/android/jni_generator/jni_generator_helper.h"

#include "base/android/jni_int_wrapper.h"

// Step 1: forward declarations.
namespace {
const char kDisplayUtilClassPath[] = "com/opera/android/utilities/DisplayUtil";
// Leaking this jclass as we cannot use LazyInstance from some threads.
base::subtle::AtomicWord g_DisplayUtil_clazz __attribute__((unused)) = 0;
#define DisplayUtil_clazz(env) base::android::LazyGetClass(env, kDisplayUtilClassPath, &g_DisplayUtil_clazz)

}  // namespace

namespace opera {

// Step 2: method stubs.

static base::subtle::AtomicWord g_DisplayUtil_isTabletFormFactor = 0;
static jboolean Java_DisplayUtil_isTabletFormFactor(JNIEnv* env) {
  CHECK_CLAZZ(env, DisplayUtil_clazz(env),
      DisplayUtil_clazz(env), false);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, DisplayUtil_clazz(env),
      "isTabletFormFactor",

"("
")"
"Z",
      &g_DisplayUtil_isTabletFormFactor);

  jboolean ret =
      env->CallStaticBooleanMethod(DisplayUtil_clazz(env),
          method_id);
  jni_generator::CheckException(env);
  return ret;
}

// Step 3: RegisterNatives.

}  // namespace opera

#endif  // com_opera_android_utilities_DisplayUtil_JNI
