// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     com/opera/android/browser/WebContentsFactory

#ifndef com_opera_android_browser_WebContentsFactory_JNI
#define com_opera_android_browser_WebContentsFactory_JNI

#include <jni.h>

#include "../../../../../../../../../../../../../../../base/android/jni_generator/jni_generator_helper.h"

#include "base/android/jni_int_wrapper.h"

// Step 1: forward declarations.
namespace {
const char kWebContentsFactoryClassPath[] =
    "com/opera/android/browser/WebContentsFactory";
// Leaking this jclass as we cannot use LazyInstance from some threads.
base::subtle::AtomicWord g_WebContentsFactory_clazz __attribute__((unused)) = 0;
#define WebContentsFactory_clazz(env) base::android::LazyGetClass(env, kWebContentsFactoryClassPath, &g_WebContentsFactory_clazz)

}  // namespace

namespace opera {

// Step 2: method stubs.

static base::android::ScopedJavaLocalRef<jobject> CreateWebContents(JNIEnv* env,
    const base::android::JavaParamRef<jclass>& jcaller,
    jboolean offTheRecord,
    jboolean initiallyHidden);

JNI_GENERATOR_EXPORT jobject
    Java_com_opera_android_browser_WebContentsFactory_nativeCreateWebContents(JNIEnv*
    env, jclass jcaller,
    jboolean offTheRecord,
    jboolean initiallyHidden) {
  return CreateWebContents(env, base::android::JavaParamRef<jclass>(env,
      jcaller), offTheRecord, initiallyHidden).Release();
}

// Step 3: RegisterNatives.

static const JNINativeMethod kMethodsWebContentsFactory[] = {
    { "nativeCreateWebContents",
"("
"Z"
"Z"
")"
"Lorg/chromium/content_public/browser/WebContents;",
    reinterpret_cast<void*>(Java_com_opera_android_browser_WebContentsFactory_nativeCreateWebContents)
    },
};

static bool RegisterNativesImpl(JNIEnv* env) {
  if (base::android::IsManualJniRegistrationDisabled()) return true;

  const int kMethodsWebContentsFactorySize =
      arraysize(kMethodsWebContentsFactory);

  if (env->RegisterNatives(WebContentsFactory_clazz(env),
                           kMethodsWebContentsFactory,
                           kMethodsWebContentsFactorySize) < 0) {
    jni_generator::HandleRegistrationError(
        env, WebContentsFactory_clazz(env), __FILE__);
    return false;
  }

  return true;
}

}  // namespace opera

#endif  // com_opera_android_browser_WebContentsFactory_JNI
