// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     com/opera/android/search/YandexPromotionTabHelper

#ifndef com_opera_android_search_YandexPromotionTabHelper_JNI
#define com_opera_android_search_YandexPromotionTabHelper_JNI

#include <jni.h>

#include "../../../../../../../../../../../../../../../base/android/jni_generator/jni_generator_helper.h"

#include "base/android/jni_int_wrapper.h"

// Step 1: forward declarations.
namespace {
const char kYandexPromotionTabHelperClassPath[] =
    "com/opera/android/search/YandexPromotionTabHelper";
// Leaking this jclass as we cannot use LazyInstance from some threads.
base::subtle::AtomicWord g_YandexPromotionTabHelper_clazz
    __attribute__((unused)) = 0;
#define YandexPromotionTabHelper_clazz(env) base::android::LazyGetClass(env, kYandexPromotionTabHelperClassPath, &g_YandexPromotionTabHelper_clazz)

}  // namespace

namespace opera {

// Step 2: method stubs.

static jlong Init(JNIEnv* env, const base::android::JavaParamRef<jobject>&
    jcaller,
    const base::android::JavaParamRef<jobject>& webContents);

JNI_GENERATOR_EXPORT jlong
    Java_com_opera_android_search_YandexPromotionTabHelper_nativeInit(JNIEnv*
    env, jobject jcaller,
    jobject webContents) {
  return Init(env, base::android::JavaParamRef<jobject>(env, jcaller),
      base::android::JavaParamRef<jobject>(env, webContents));
}

JNI_GENERATOR_EXPORT void
    Java_com_opera_android_search_YandexPromotionTabHelper_nativeAskToSetAsDefaultReply(JNIEnv*
    env, jobject jcaller,
    jlong nativeYandexPromotionTabHelper,
    jint requestId) {
  YandexPromotionTabHelper* native =
      reinterpret_cast<YandexPromotionTabHelper*>(nativeYandexPromotionTabHelper);
  CHECK_NATIVE_PTR(env, jcaller, native, "AskToSetAsDefaultReply");
  return native->AskToSetAsDefaultReply(env,
      base::android::JavaParamRef<jobject>(env, jcaller), requestId);
}

static base::subtle::AtomicWord g_YandexPromotionTabHelper_destroy = 0;
static void Java_YandexPromotionTabHelper_destroy(JNIEnv* env, const
    base::android::JavaRefOrBare<jobject>& obj) {
  CHECK_CLAZZ(env, obj.obj(),
      YandexPromotionTabHelper_clazz(env));
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, YandexPromotionTabHelper_clazz(env),
      "destroy",

"("
")"
"V",
      &g_YandexPromotionTabHelper_destroy);

     env->CallVoidMethod(obj.obj(),
          method_id);
  jni_generator::CheckException(env);

}

static base::subtle::AtomicWord g_YandexPromotionTabHelper_canAskToSetAsDefault
    = 0;
static jboolean Java_YandexPromotionTabHelper_canAskToSetAsDefault(JNIEnv* env,
    const base::android::JavaRefOrBare<jobject>& obj, const
    base::android::JavaRefOrBare<jstring>& engine) {
  CHECK_CLAZZ(env, obj.obj(),
      YandexPromotionTabHelper_clazz(env), false);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, YandexPromotionTabHelper_clazz(env),
      "canAskToSetAsDefault",

"("
"Ljava/lang/String;"
")"
"Z",
      &g_YandexPromotionTabHelper_canAskToSetAsDefault);

  jboolean ret =
      env->CallBooleanMethod(obj.obj(),
          method_id, engine.obj());
  jni_generator::CheckException(env);
  return ret;
}

static base::subtle::AtomicWord g_YandexPromotionTabHelper_askToSetAsDefault =
    0;
static void Java_YandexPromotionTabHelper_askToSetAsDefault(JNIEnv* env, const
    base::android::JavaRefOrBare<jobject>& obj, const
    base::android::JavaRefOrBare<jstring>& engine,
    JniIntWrapper requestId) {
  CHECK_CLAZZ(env, obj.obj(),
      YandexPromotionTabHelper_clazz(env));
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, YandexPromotionTabHelper_clazz(env),
      "askToSetAsDefault",

"("
"Ljava/lang/String;"
"I"
")"
"V",
      &g_YandexPromotionTabHelper_askToSetAsDefault);

     env->CallVoidMethod(obj.obj(),
          method_id, engine.obj(), as_jint(requestId));
  jni_generator::CheckException(env);

}

// Step 3: RegisterNatives.

static const JNINativeMethod kMethodsYandexPromotionTabHelper[] = {
    { "nativeInit",
"("
"Lorg/chromium/content_public/browser/WebContents;"
")"
"J",
    reinterpret_cast<void*>(Java_com_opera_android_search_YandexPromotionTabHelper_nativeInit)
    },
    { "nativeAskToSetAsDefaultReply",
"("
"J"
"I"
")"
"V",
    reinterpret_cast<void*>(Java_com_opera_android_search_YandexPromotionTabHelper_nativeAskToSetAsDefaultReply)
    },
};

static bool RegisterNativesImpl(JNIEnv* env) {
  if (base::android::IsManualJniRegistrationDisabled()) return true;

  const int kMethodsYandexPromotionTabHelperSize =
      arraysize(kMethodsYandexPromotionTabHelper);

  if (env->RegisterNatives(YandexPromotionTabHelper_clazz(env),
                           kMethodsYandexPromotionTabHelper,
                           kMethodsYandexPromotionTabHelperSize) < 0) {
    jni_generator::HandleRegistrationError(
        env, YandexPromotionTabHelper_clazz(env), __FILE__);
    return false;
  }

  return true;
}

}  // namespace opera

#endif  // com_opera_android_search_YandexPromotionTabHelper_JNI
