#include "mobile/jni/invokes.inc"
#include "bream/vm/c/graphics/invokes.inc"
#include "mini/c/shared/generic/vm_integ/VMInvokesMetaViewport.inc"
#include "mini/c/shared/generic/vm_integ/VMInvokesObml.inc"
#include "mini/c/shared/generic/vm_integ/VMInvokesUtils.inc"

#ifdef MOP_FEATURE_ODP
#include "mini/c/shared/generic/vm_integ/VMInvokesAsyncBrowser.inc"
#include "mini/c/shared/generic/vm_integ/VMInvokesOdp.inc"
#endif
